# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mlx90640',
                'doc_host': 'https://eandreas.github.io',
                'git_url': 'https://github.com/eandreas/mlx90640',
                'lib_path': 'mlx90640'},
  'syms': {'mlx90640.core': {'mlx90640.core.foo': ('core.html#foo', 'mlx90640/core.py')}}}
